package org.alliancegenome.curation_api.enums;

public enum BackendBulkLoadType {
	GENE_DTO, ALLELE_DTO, AGM_DTO, DISEASE_ANNOTATION_DTO, DISEASE_ANNOTATION, GENE, ALLELE, AGM, AGM_DISEASE_ANNOTATION, ALLELE_DISEASE_ANNOTATION, GENE_DISEASE_ANNOTATION, ONTOLOGY, MOLECULE,
	FULL_INGEST, RESOURCE_DESCRIPTOR;
}
