version: "3.2"

services:

  curation.app:
    container_name: agr.curation.${NET}.api.server
    image: 100225593120.dkr.ecr.us-east-1.amazonaws.com/agr_curation:${AGR_CURATION_RELEASE}
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://logs.alliancegenome.internal:12201'
    ports:
      - "8080:8080"
    networks:
      - curation
    env_file:
      - .env

networks:
  # The presence of these objects is sufficient to define them
  curation:
