version: "3.2"

services:
  activemq:
    container_name: curation.activemq
    image: vromero/activemq-artemis:2.9.0-alpine
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
    networks:
      - curation
    environment:
      - ARTEMIS_USERNAME=quarkus
      - ARTEMIS_PASSWORD=quarkus

  cerebro:
    container_name: curation.cerebro
    image: yannart/cerebro
    ports:
      - "9000:9000"
    networks:
      - curation
    depends_on:
      - "elasticsearch"

  elasticsearch:
    container_name: curation.elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - curation
    environment:
      - discovery.type=single-node

  curation.app:
    container_name: curation.app
    image: 100225593120.dkr.ecr.us-east-1.amazonaws.com/agr_curation:0.0.4
    networks:
      - curation
    environment:
      - QUARKUS_ARTEMIS_URL=tcp://curation.activemq:61616
      - QUARKUS_ARTEMIS_PASSWORD=quarkus
      - QUARKUS_ARTEMIS_USERNAME=quarkus
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://curation-db.cmnnhlso7wdi.us-east-1.rds.amazonaws.com:5432/curation
      # - QUARKUS_DATASOURCE_PASSWORD=${QUARKUS_DATASOURCE_PASSWORD}
      # - QUARKUS_DATASOURCE_USERNAME=${QUARKUS_DATASOURCE_USERNAME}
      - QUARKUS_HIBERNATE_SEARCH_ORM_ELASTICSEARCH_HOSTS=curation.elasticsearch:9200
    env_file:
      - .env
    depends_on:
      - "elasticsearch"
      - "activemq"

networks:
  # The presence of these objects is sufficient to define them
  curation:
