version: "3.2"

services:

  curation.app:
    container_name: agr.curation.api.server
    image: 100225593120.dkr.ecr.us-east-1.amazonaws.com/agr_curation:${AGR_CURATION_RELEASE}
    ports:
      - "8080:8080"
    networks:
      - curation
    environment:
      - QUARKUS_DATASOURCE_USERNAME=${QUARKUS_DATASOURCE_USERNAME}
      - QUARKUS_DATASOURCE_PASSWORD=${QUARKUS_DATASOURCE_PASSWORD}
      - QUARKUS_DATASOURCE_JDBC_URL=${QUARKUS_DATASOURCE_JDBC_URL}
      - QUARKUS_HIBERNATE_SEARCH_ORM_ELASTICSEARCH_HOSTS=${QUARKUS_HIBERNATE_SEARCH_ORM_ELASTICSEARCH_HOSTS}
      - QUARKUS_HIBERNATE_SEARCH_ORM_ELASTICSEARCH_PROTOCOL=${QUARKUS_HIBERNATE_SEARCH_ORM_ELASTICSEARCH_PROTOCOL}
      - QUARKUS_QPID_JMS_URL=${QUARKUS_QPID_JMS_URL}
      - QUARKUS_QPID_JMS_USERNAME=${QUARKUS_QPID_JMS_USERNAME}
      - QUARKUS_QPID_JMS_PASSWORD=${QUARKUS_QPID_JMS_PASSWORD}
    env_file:
      - .env

networks:
  # The presence of these objects is sufficient to define them
  curation:
