FROM openjdk:11

WORKDIR /agr_curation

ADD target/agr_curation_api-runner.jar .

EXPOSE 8080

ENV QUARKUS_DATASOURCE_JDBC_URL jdbc:postgresql://localhost:5432/curation
ENV QUARKUS_DATASOURCE_USERNAME postgres
ENV QUARKUS_DATASOURCE_PASSWORD postgres

ENV QUARKUS_HIBERNATE_SEARCH_ORM_ELASTICSEARCH_HOSTS localhost:9200
ENV QUARKUS_HIBERNATE_SEARCH_ORM_ELASTICSEARCH_PROTOCOL http

ENV QUARKUS_QPID_JMS_URL amqp://localhost:5672
ENV QUARKUS_QPID_JMS_USERNAME quarkus
ENV QUARKUS_QPID_JMS_PASSWORD quarkus

CMD ["java", "-jar", "agr_curation_api-runner.jar"]
