package org.alliancegenome.curation_api.model.entities.interfaces;

/**
 * SCRUM-6359 / SCRUM-6360 — implemented by every entity that carries an AGRKB curie, so one
 * minting component can serve all of them.
 *
 * The field is declared twice in the entity model, in sibling branches under AuditedObject:
 * {@code CurieObject} (-> SubmittedObject -> BiologicalEntity / Reagent, i.e. Gene, Allele,
 * Variant, AGM, Construct, Antibody, STR, AssemblyComponent, GenomeAssembly) and
 * {@code Annotation} (-> DiseaseAnnotation, PhenotypeAnnotation). There is no common supertype
 * exposing the accessors, so this interface supplies the generic bound that
 * {@code CurieMintService} and {@code BaseCurieSQLDAO} need.
 *
 * Both accessors are already generated by Lombok on the declaring classes, so implementing this
 * adds no code and changes no behaviour.
 */
public interface CurieCarrier {

	String getCurie();

	void setCurie(String curie);

}
