package org.alliancegenome.curation_api.constants;

import java.util.ArrayList;
import java.util.List;

public final class CrossReferenceConstants {

	private CrossReferenceConstants() {
		// Hidden from view, as it is a utility class
	}

	/**
	 * Page areas for the phenotype cross references the Alliance generates itself during phenotype
	 * annotation loads (see GenePhenotypeAnnotationXrefHelper).
	 */
	public static final List<String> ALLIANCE_DERIVED_PHENOTYPE_PAGE_AREAS = List.of(
		"gene/phenotypes",
		"gene/phenotypes_impc"
	);

	/**
	 * All page areas whose cross references are generated by the Alliance during annotation loads
	 * (see GenePhenotypeAnnotationXrefHelper and GeneXrefHelper) rather than being supplied in a MOD
	 * submission file. Entity loads must not delete these, as the submitted cross reference list,
	 * which is otherwise authoritative, never contains them.
	 */
	public static final List<String> ALLIANCE_DERIVED_PAGE_AREAS = buildDerivedPageAreas();

	private static List<String> buildDerivedPageAreas() {
		List<String> pageAreas = new ArrayList<>(ALLIANCE_DERIVED_PHENOTYPE_PAGE_AREAS);
		pageAreas.add("gene/other_expression");
		pageAreas.add("biogrid/orcs");
		pageAreas.add("expression_atlas");
		return List.copyOf(pageAreas);
	}

}
