export const data = {
    "entity": {
        "MATerm": { "esCount": 3230, "dbCount": 3230 },
        "FBDVTerm": { "esCount": 207, "dbCount": 207 },
        "Vocabulary": { "esCount": 16, "dbCount": 16 },
        "StageTerm": { "esCount": 0, "dbCount": 1248 },
        "GeneSynonymSlotAnnotation": { "esCount": 0, "dbCount": 466888 },
        "OntologyTerm": { "esCount": 0, "dbCount": 319426 },
        "CurationReportGroup": { "esCount": 0, "dbCount": 0 },
        "GeneSystematicNameSlotAnnotation": { "esCount": 0, "dbCount": 239244 },
        "BulkFMSLoad": { "esCount": 0, "dbCount": 1 },
        "Gene": { "esCount": 390204, "dbCount": 390204 },
        "SlotAnnotation": { "esCount": 0, "dbCount": 6833725 },
        "XSMOTerm": { "esCount": 326, "dbCount": 326 },
        "GeneFullNameSlotAnnotation": { "esCount": 0, "dbCount": 679927 },
        "DOTerm": { "esCount": 13678, "dbCount": 13678 },
        "ECOTerm": { "esCount": 1975, "dbCount": 1975 },
        "ConditionRelation": { "esCount": 1776, "dbCount": 1776 },
        "WBBTTerm": { "esCount": 7190, "dbCount": 7190 },
        "BulkLoad": { "esCount": 0, "dbCount": 51 },
        "CurationReport": { "esCount": 0, "dbCount": 0 },
        "ROTerm": { "esCount": 0, "dbCount": 0 },
        "AGMDiseaseAnnotation": { "esCount": 11403, "dbCount": 11403 },
        "XCOTerm": { "esCount": 961, "dbCount": 961 },
        "BulkManualLoad": { "esCount": 0, "dbCount": 26 },
        "AlleleMutationTypeSlotAnnotation": { "esCount": 0, "dbCount": 1 },
        "NameSlotAnnotation": { "esCount": 0, "dbCount": 6828355 },
        "ZFSTerm": { "esCount": 54, "dbCount": 54 },
        "BulkScheduledLoad": { "esCount": 0, "dbCount": 25 },
        "Molecule": { "esCount": 3748, "dbCount": 3748 },
        "ResourceDescriptorPage": { "esCount": 183, "dbCount": 183 },
        "EMAPATerm": { "esCount": 8021, "dbCount": 8021 },
        "VocabularyTerm": { "esCount": 197, "dbCount": 197 },
        "Note": { "esCount": 0, "dbCount": 22622 },
        "ChemicalTerm": { "esCount": 0, "dbCount": 167823 },
        "OBITerm": { "esCount": 3881, "dbCount": 3881 },
        "Synonym": { "esCount": 0, "dbCount": 2185913 },
        "CurationReportHistory": { "esCount": 0, "dbCount": 0 },
        "Person": { "esCount": 0, "dbCount": 53 },
        "ZFATerm": { "esCount": 3144, "dbCount": 3144 },
        "GenomicEntity": { "esCount": 0, "dbCount": 3518820 },
        "BulkLoadGroup": { "esCount": 0, "dbCount": 7 },
        "BulkLoadFileException": { "esCount": 0, "dbCount": 946632 },
        "Organization": { "esCount": 10, "dbCount": 10 },
        "CHEBITerm": { "esCount": 163749, "dbCount": 163749 },
        "BiologicalEntity": { "esCount": 0, "dbCount": 3518820 },
        "AlleleInheritanceModeSlotAnnotation": { "esCount": 0, "dbCount": 5368 },
        "XBSTerm": { "esCount": 97, "dbCount": 97 }, 
        "BulkLoadFileHistory": { "esCount": 0, "dbCount": 221 },
        "XPOTerm": { "esCount": 21059, "dbCount": 21059 },
        "SOTerm": { "esCount": 2597, "dbCount": 2597 },
        "GeneDiseaseAnnotation": { "esCount": 37242, "dbCount": 37242 },
        "DataProvider": { "esCount": 0, "dbCount": 57 },
        "VocabularyTermSet": { "esCount": 6, "dbCount": 6 },
        "ATPTerm": { "esCount": 135, "dbCount": 135 },
        "ExperimentalCondition": { "esCount": 481, "dbCount": 481 },
        "Association": { "esCount": 0, "dbCount": 60602 },
        "WBLSTerm": { "esCount": 777, "dbCount": 777 },
        "PhenotypeTerm": { "esCount": 0, "dbCount": 35211 },
        "BulkURLLoad": { "esCount": 0, "dbCount": 24 },
        "AlleleFullNameSlotAnnotation": { "esCount": 0, "dbCount": 1197176 },
        "AlleleSecondaryIdSlotAnnotation": { "esCount": 0, "dbCount": 1 },
        "LoggedInPerson": { "esCount": 0, "dbCount": 37 },
        "NCBITaxonTerm": { "esCount": 895, "dbCount": 895 },
        "AlleleSymbolSlotAnnotation": { "esCount": 0, "dbCount": 3002462 },
        "MPTerm": { "esCount": 14151, "dbCount": 14151 },
        "XBATerm": { "esCount": 1677, "dbCount": 1677 },
        "GOTerm": { "esCount": 47564, "dbCount": 47564 },
        "MMUSDVTerm": { "esCount": 113, "dbCount": 113 },
        "InformationContentEntity": { "esCount": 0, "dbCount": 311077 },
        "AnatomicalTerm": { "esCount": 0, "dbCount": 43102 },
        "ExperimentalConditionOntologyTerm": { "esCount": 0, "dbCount": 1122 },
        "Reference": { "esCount": 956237, "dbCount": 311077 },
        "GeneSymbolSlotAnnotation": { "esCount": 0, "dbCount": 797524 },
        "AlleleDiseaseAnnotation": { "esCount": 11956, "dbCount": 11956 },
        "BulkLoadFile": { "esCount": 0, "dbCount": 252 },
        "DAOTerm": { "esCount": 19840, "dbCount": 19840 },
        "ZECOTerm": { "esCount": 161, "dbCount": 161 },
        "Allele": { "esCount": 2932029, "dbCount": 2932029 },
        "XBEDTerm": { "esCount": 195, "dbCount": 195 }, 
        "AllianceMember": { "esCount": 0, "dbCount": 8 },
        "DiseaseAnnotation": { "esCount": 0, "dbCount": 60601 },
        "AffectedGenomicModel": { "esCount": 196587, "dbCount": 196587 },
        "CrossReference": { "esCount": 0, "dbCount": 1052011 },
        "AlleleSynonymSlotAnnotation": { "esCount": 0, "dbCount": 0 },
        "PersonSetting": { "esCount": 0, "dbCount": 85 },
        "ResourceDescriptor": { "esCount": 68, "dbCount": 68 }
    }
}

export const settings = {
    "filters": {}
}


