ALTER TABLE ONLY public.allele_note ADD CONSTRAINT uk_3ja9wii4jxp0krcfpturumjhb UNIQUE (relatednotes_id);
ALTER TABLE ONLY public.diseaseannotation ADD CONSTRAINT uk_hvn7cmiviowf91epvfp1r67vy UNIQUE (modinternalid);
ALTER TABLE ONLY public.resourcedescriptor ADD CONSTRAINT uk_lo96grpf2bfqck54wnunlwhm UNIQUE (prefix);

CREATE INDEX allelediseaseannotation_inferredgene_index ON public.allelediseaseannotation USING btree (inferredgene_curie);
CREATE INDEX allelediseaseannotation_subject_index ON public.allelediseaseannotation USING btree (subject_curie);
CREATE INDEX biologicalentity_dataprovider_index ON public.biologicalentity USING btree (dataprovider_id);
CREATE INDEX genefullname_singlegene_curie_index ON public.genefullnameslotannotation USING btree (singlegene_curie);
CREATE INDEX genesynonym_singlegene_curie_index ON public.genesynonymslotannotation USING btree (singlegene_curie);
CREATE INDEX genesystematicname_singlegene_curie_index ON public.genesystematicnameslotannotation USING btree (singlegene_curie);
CREATE INDEX idx3ja9wii4jxp0krcfpturumjhb ON public.allele_note USING btree (relatednotes_id);
CREATE INDEX idx50j986kkb5ymfepkamokl1q9w ON public.allele_note USING btree (allele_curie);
CREATE INDEX idx5f73olsmf7f70k9nimewmv2ov ON public.reference_crossreference USING btree (crossreferences_id);
CREATE INDEX idxby7378djairi7w4hvj0bw8n64 ON public.vocabularyterm_synonyms USING btree (vocabularyterm_id);
CREATE INDEX idxdm4w3r1x3dg78s2mxotkgqwq ON public.vocabularyterm_crossreference USING btree (crossreferences_id);
CREATE INDEX idxf6sdkewbxohussr4fs7440vj5 ON public.allelediseaseannotation_gene USING btree (assertedgenes_curie);
CREATE INDEX idxk4kbcn96bs4gafx883i9sj7my ON public.note_reference USING btree (note_id);
CREATE INDEX idxkt8n3ru0rs78kdihpq7612is1 ON public.note_reference USING btree (references_curie);
CREATE INDEX idxl887mndcbaxqnxek5xvd55wj3 ON public.resourcedescriptor_synonyms USING btree (resourcedescriptor_id);
CREATE INDEX idxo6e5hexti6nfdj1v6ytnlwjvd ON public.allele_reference USING btree (allele_curie);
CREATE INDEX note_createdby_index ON public.note USING btree (createdby_id);
CREATE INDEX note_notetype_index ON public.note USING btree (notetype_id);
CREATE INDEX note_updatedby_index ON public.note USING btree (updatedby_id);
CREATE INDEX organization_homepageresourcedescriptorpage_id_index ON public.organization USING btree (homepageresourcedescriptorpage_id);
CREATE INDEX resourcedescriptorpage_createdby_id_index ON public.resourcedescriptorpage USING btree (createdby_id);
CREATE INDEX resourcedescriptorpage_resourcedescriptor_id_index ON public.resourcedescriptorpage USING btree (resourcedescriptor_id);
CREATE INDEX resourcedescriptorpage_updatedby_id_index ON public.resourcedescriptorpage USING btree (updatedby_id);

CREATE INDEX diseaseannotation_annotationtype_index ON public.diseaseannotation USING btree (annotationtype_id);
CREATE INDEX diseaseannotation_createdby_index ON public.association USING btree (createdby_id);
CREATE INDEX diseaseannotation_dataprovider_index ON public.diseaseannotation USING btree (dataprovider_id);
CREATE INDEX diseaseannotation_diseasegeneticmodifierrelation_index ON public.diseaseannotation USING btree (diseasegeneticmodifierrelation_id);
CREATE INDEX diseaseannotation_diseaserelation_index ON public.diseaseannotation USING btree (diseaserelation_id);
CREATE INDEX diseaseannotation_geneticsex_index ON public.diseaseannotation USING btree (geneticsex_id);
CREATE INDEX diseaseannotation_object_index ON public.diseaseannotation USING btree (object_curie);
CREATE INDEX diseaseannotation_secondarydataprovider_index ON public.diseaseannotation USING btree (secondarydataprovider_id);
CREATE INDEX diseaseannotation_singlereference_index ON public.diseaseannotation USING btree (singlereference_curie);
CREATE INDEX diseaseannotation_updatedby_index ON public.association USING btree (updatedby_id);
CREATE INDEX genesymbol_singlegene_curie_index ON public.genesymbolslotannotation USING btree (singlegene_curie);
CREATE INDEX idx2nxnuty631qew681vvjn4wd75 ON public.diseaseannotation_note USING btree (diseaseannotation_id);
CREATE INDEX idx3u0swr7xss7wjjve7ocd08u27 ON public.diseaseannotation_ecoterm USING btree (evidencecodes_curie);
CREATE INDEX idx42skj23oouce6tf5x57pxycba ON public.diseaseannotation_note USING btree (relatednotes_id);
CREATE INDEX idxa408leg4b6rrhx0e0e35yno7t ON public.diseaseannotation_biologicalentity USING btree (diseaseannotation_id);
CREATE INDEX idxbnb14fsatd291upd9af38fnyp ON public.diseaseannotation_vocabularyterm USING btree (diseasequalifiers_id);
CREATE INDEX idxc8bxs3ggb4rt2kmnqja0js5mq ON public.diseaseannotation_gene USING btree (with_curie);
CREATE INDEX idxc8oiw5qoippfjl0b6s9oegiss ON public.diseaseannotation_vocabularyterm USING btree (diseaseannotation_id);
CREATE INDEX idxhnh1h715wjhoulhu2k77ibdfs ON public.diseaseannotation_conditionrelation USING btree (diseaseannotation_id);
CREATE INDEX idxntbiegjxs3ooqy894m4y5vgwb ON public.diseaseannotation_ecoterm USING btree (diseaseannotation_id);
CREATE INDEX idxon9a94gwp0jl6t2sfjqv0iwa5 ON public.diseaseannotation_biologicalentity USING btree (diseasegeneticmodifiers_curie);
CREATE INDEX idxtrk7q1phvahyem27wlkmiyw8w ON public.diseaseannotation_conditionrelation USING btree (conditionrelations_id);

ALTER TABLE ONLY public.dataprovider_aud ADD CONSTRAINT fk66rd9ltf5l9paxmvyr63tcqwf FOREIGN KEY (rev) REFERENCES public.revinfo(rev);
ALTER TABLE ONLY public.crossreference ADD CONSTRAINT fkakjy736v2tfb6amt6bgvub0j3 FOREIGN KEY (createdby_id) REFERENCES public.person(id);
ALTER TABLE ONLY public.dataprovider ADD CONSTRAINT fkblfxj0208nodh91pjkttkluqr FOREIGN KEY (createdby_id) REFERENCES public.person(id);
ALTER TABLE ONLY public.alleleinheritancemodeslotannotation ADD CONSTRAINT fkcgj3a3skh2a666q8wvehcs1pw FOREIGN KEY (singleallele_curie) REFERENCES public.allele(curie);
ALTER TABLE ONLY public.genesecondaryidslotannotation ADD CONSTRAINT fkhtdt6peje2s446u44ax3knp14 FOREIGN KEY (singlegene_curie) REFERENCES public.gene(curie);
ALTER TABLE ONLY public.allelegermlinetransmissionstatusslotannotation ADD CONSTRAINT fkimjfrsvtapxj0gl4ocsfc68iy FOREIGN KEY (id) REFERENCES public.slotannotation(id);
ALTER TABLE ONLY public.allelefunctionalimpactslotannotation ADD CONSTRAINT fkng1x5duqyvks0enxdtr7andrl FOREIGN KEY (id) REFERENCES public.slotannotation(id);
ALTER TABLE ONLY public.allelesecondaryidslotannotation ADD CONSTRAINT fko6369ool2dxdy8odi2i9brj4r FOREIGN KEY (id) REFERENCES public.secondaryidslotannotation(id);
ALTER TABLE ONLY public.genesecondaryidslotannotation ADD CONSTRAINT fkq0oks812epecjvubiasibhw2s FOREIGN KEY (id) REFERENCES public.secondaryidslotannotation(id);
ALTER TABLE ONLY public.dataprovider ADD CONSTRAINT fkq3rkybeijrxnxd1t5hh4c8kmv FOREIGN KEY (updatedby_id) REFERENCES public.person(id);
ALTER TABLE ONLY public.crossreference_aud ADD CONSTRAINT fkricj7nn0u0fec2l2r2fo7al55 FOREIGN KEY (rev) REFERENCES public.revinfo(rev);
ALTER TABLE ONLY public.crossreference ADD CONSTRAINT fksk2d4ch9lg6kyy03b6mrwp85v FOREIGN KEY (updatedby_id) REFERENCES public.person(id);
