ALTER TABLE experimentalcondition ALTER COLUMN uniqueid TYPE VARCHAR(3500);
ALTER TABLE conditionrelation ALTER COLUMN uniqueid TYPE VARCHAR(3500);
ALTER TABLE annotation ALTER COLUMN uniqueid TYPE VARCHAR(3500);