ALTER INDEX agmsequencetargetingreagentassociation_agmassociationsubject_in RENAME TO AgmStrAssociation_agmAssociationSubject_index;
ALTER INDEX agmsequencetargetingreagentassociation_agmsequencetargetingreag RENAME TO AgmStrAssociation_AgmStrAssociationObject_index;
ALTER INDEX agmsequencetargetingreagentassociation_createdby_index RENAME TO AgmStrAssociation_createdBy_index;
ALTER INDEX agmsequencetargetingreagentassociation_internal_index RENAME TO AgmStrAssociation_internal_index;
ALTER INDEX agmsequencetargetingreagentassociation_obsolete_index RENAME TO AgmStrAssociation_obsolete_index;
ALTER INDEX agmsequencetargetingreagentassociation_relation_index RENAME TO AgmStrAssociation_relation_index;
ALTER INDEX agmsequencetargetingreagentassociation_updatedby_index RENAME TO AgmStrAssociation_updatedBy_index;

ALTER INDEX htpexpressiondatasetsampleannotation_dataprovider_index RENAME TO htpdatasample_dataprovider_index;
ALTER INDEX htpexpressiondatasetsampleannotation_dataproviderxref_index RENAME TO htpdatasample_dataproviderxref_index;

ALTER INDEX htpexpressiondatasetannotation_dataprovider_index RENAME TO htpdatasetannotation_dataprovider_index
ALTER INDEX htpexpressiondatasetannotation_dataprovidercrossreference_index RENAME TO htpdatasetannotation_dataprovidercrossreference_index;


