ALTER TABLE CodingSequenceGenomicLocationAssociation RENAME TO CDSGLAssociation;
ALTER TABLE CodingSequenceGenomicLocationAssociation_InformationContentEntity RENAME TO CDSGLAssociation_InformationContentEntity;
ALTER TABLE SequenceTargetingReagentGeneAssociation RENAME TO SQTRGeneAssociation;
ALTER TABLE SequenceTargetingReagentGeneAssociation_InformationContentEntity RENAME TO SQTRGeneAssociation_InformationContentEntity;
