CREATE TABLE externaldatabasereference (
	id BIGINT CONSTRAINT externaldatabasereference_pkey PRIMARY KEY
);

ALTER TABLE externaldatabasereference ADD CONSTRAINT externaldatabasereference_id_fk FOREIGN KEY (id) REFERENCES informationcontententity(id);

ALTER TABLE diseaseannotation RENAME COLUMN singlereference_id TO evidenceitem_id;
ALTER TABLE geneexpressionannotation RENAME COLUMN singlereference_id TO evidenceitem_id;
ALTER TABLE phenotypeannotation RENAME COLUMN singlereference_id TO evidenceitem_id;

ALTER TABLE diseaseannotation RENAME CONSTRAINT diseaseannotation_singlereference_id_fk TO diseaseannotation_evidenceitem_id_fk;
ALTER TABLE geneexpressionannotation RENAME CONSTRAINT geneexpressionannotation_singlereference_id_fk TO geneexpressionannotation_evidenceitem_id_fk;
ALTER TABLE phenotypeannotation RENAME CONSTRAINT phenotypeannotation_singlereference_id_fk TO phenotypeannotation_evidenceitem_id_fk;

ALTER INDEX diseaseannotation_singlereference_index RENAME TO diseaseannotation_evidenceitem_index;
ALTER INDEX geneexpressionannotation_singlereference_index RENAME TO geneexpressionannotation_evidenceitem_index;
ALTER INDEX phenotypeannotation_singlereference_index RENAME TO phenotypeannotation_evidenceitem_index;