export const CLASSES = Object.freeze({
	Gene: { name: 'Genes', link: '/#/genes', type: 'entity', hasTable: true, isIndexed: true },
	Allele: { name: 'Alleles', link: '/#/alleles', type: 'entity', hasTable: true, isIndexed: true },
	AffectedGenomicModel: {
		name: 'Affected Genomic Models',
		link: '/#/agms',
		type: 'entity',
		hasTable: true,
		isIndexed: true,
	},
	Variant: { name: 'Variants', link: '/#/variants', type: 'entity', hasTable: true, isIndexed: true },
	DiseaseAnnotation: {
		name: 'Disease Annotations',
		link: '/#/diseaseAnnotations',
		type: 'entity',
		hasTable: true,
		isIndexed: false,
	},
	AGMDiseaseAnnotation: {
		name: 'AGM Disease Annotations',
		link: '/#/diseaseAnnotations',
		type: 'entity',
		hasTable: false,
		isIndexed: true,
	},
	AlleleDiseaseAnnotation: {
		name: 'Allele Disease Annotations',
		link: '/#/diseaseAnnotations',
		type: 'entity',
		hasTable: false,
		isIndexed: true,
	},
	GeneDiseaseAnnotation: {
		name: 'Gene Disease Annotations',
		link: '/#/diseaseAnnotations',
		type: 'entity',
		hasTable: false,
		isIndexed: true,
	},
	PhenotypeAnnotation: {
		name: 'Phenotype Annotations',
		link: '/#/phenotypeAnnotations',
		type: 'entity',
		hasTable: true,
		isIndexed: false,
	},
	AGMPhenotypeAnnotation: {
		name: 'AGM Phenotype Annotations',
		link: '/#/phenotypeAnnotations',
		type: 'entity',
		hasTable: false,
		isIndexed: true,
	},
	AllelePhenotypeAnnotation: {
		name: 'Allele Phenotype Annotations',
		link: '/#/phenotypeAnnotations',
		type: 'entity',
		hasTable: false,
		isIndexed: true,
	},
	GenePhenotypeAnnotation: {
		name: 'Gene Phenotype Annotations',
		link: '/#/phenotypeAnnotations',
		type: 'entity',
		hasTable: false,
		isIndexed: true,
	},
	GeneGeneticInteraction: {
		name: 'Gene Genetic Interactions',
		link: '/#/geneGeneticInteractions',
		type: 'entity',
		hasTable: true,
		isIndexed: true,
	},
	GeneMolecularInteraction: {
		name: 'Gene Molecular Interactions',
		link: '/#/geneMolecularInteractions',
		type: 'entity',
		hasTable: true,
		isIndexed: true,
	},
	ExperimentalCondition: {
		name: 'Experimental Conditions',
		link: '/#/experimentalConditions',
		type: 'entity',
		hasTable: true,
		isIndexed: true,
	},
	ConditionRelation: {
		name: 'Condition Relations',
		link: '/#/conditionRelations',
		type: 'entity',
		hasTable: true,
		isIndexed: true,
	},
	Construct: { name: 'Constructs', link: '/#/constructs', type: 'entity', hasTable: true, isIndexed: true },
	Molecule: { name: 'Molecules', link: '/#/molecules', type: 'entity', hasTable: true, isIndexed: true },
	Reference: { name: 'Literature References', link: '/#/references', type: 'entity', hasTable: true, isIndexed: false },
	SequenceTargetingReagent: {
		name: 'Sequence Targeting Reagents',
		type: 'entity',
		hasTable: false,
		isIndexed: true,
	},
	Species: { name: 'Species', link: '/#/species', type: 'entity', hasTable: true, isIndexed: true },
	Transcript: { name: 'Transcripts', type: 'entity', hasTable: false, isIndexed: false },
	Exon: { name: 'Exons', type: 'entity', hasTable: false, isIndexed: false },
	CodingSequence: {
		name: 'Coding Sequences',
		type: 'entity',
		hasTable: false,
		isIndexed: false,
	},
	AssemblyComponent: {
		name: 'Assembly Components',
		type: 'entity',
		hasTable: false,
		isIndexed: false,
	},
	GenomeAssembly: {
		name: 'Genome Assemblies',
		type: 'entity',
		hasTable: false,
		isIndexed: true,
	},
	GeneExpressionAnnotation: {
		name: 'Gene Expression Annotations',
		type: 'entity',
		hasTable: false,
		isIndexed: true,
	},
	PredictedVariantConsequence: {
		name: 'Predicted Variant Consequences',
		type: 'entity',
		hasTable: false,
		isIndexed: false,
	},
	HTPExpressionDatasetAnnotation: {
		name: 'HTP Expression Dataset Annotations',
		type: 'entity',
		hasTable: false,
		isIndexed: false,
	},
	HTPExpressionDatasetSampleAnnotation: {
		name: 'HTP Expression Dataset Sample Annotations',
		type: 'entity',
		hasTable: false,
		isIndexed: false,
	},
	GeneOntologyAnnotation: {
		name: 'Gene Ontology Annotations',
		type: 'entity',
		hasTable: false,
		isIndexed: false,
	},
	GeneToGeneParalogy: { name: 'Paralogy', type: 'entity', hasTable: false, isIndexed: false },
	GeneToGeneOrthology: { name: 'Orthology', type: 'entity', hasTable: false, isIndexed: false },

	DOTerm: { name: 'DO', link: '/#/ontology/do', type: 'ontology', hasTable: true, isIndexed: true },
	CHEBITerm: { name: 'CHEBI', link: '/#/ontology/chebi', type: 'ontology', hasTable: true, isIndexed: true },
	XSMOTerm: { name: 'XSMO', link: '/#/ontology/xsmo', type: 'ontology', hasTable: true, isIndexed: true },
	ECOTerm: { name: 'ECO', link: '/#/ontology/eco', type: 'ontology', hasTable: true, isIndexed: true },
	SOTerm: { name: 'SO', link: '/#/ontology/so', type: 'ontology', hasTable: true, isIndexed: true },
	GOTerm: { name: 'GO', link: '/#/ontology/go', type: 'ontology', hasTable: true, isIndexed: true },
	MATerm: { name: 'MA', link: '/#/ontology/ma', type: 'ontology', hasTable: true, isIndexed: true },
	ZFATerm: { name: 'ZFA', link: '/#/ontology/zfa', type: 'ontology', hasTable: true, isIndexed: true },
	MPTerm: { name: 'MP', link: '/#/ontology/mp', type: 'ontology', hasTable: true, isIndexed: true },
	DAOTerm: { name: 'DAO', link: '/#/ontology/dao', type: 'ontology', hasTable: true, isIndexed: true },
	EMAPATerm: { name: 'EMAPA', link: '/#/ontology/emapa', type: 'ontology', hasTable: true, isIndexed: true },
	WBBTTerm: { name: 'WBBT', link: '/#/ontology/wbbt', type: 'ontology', hasTable: true, isIndexed: true },
	XBATerm: { name: 'XBA', link: '/#/ontology/xba', type: 'ontology', hasTable: true, isIndexed: true },
	XBSTerm: { name: 'XBS', link: '/#/ontology/xbs', type: 'ontology', hasTable: true, isIndexed: true },
	XCOTerm: { name: 'XCO', link: '/#/ontology/xco', type: 'ontology', hasTable: true, isIndexed: true },
	ROTerm: { name: 'RO', link: '/#/ontology/ro', type: 'ontology', hasTable: true, isIndexed: true },
	ZECOTerm: { name: 'ZECO', link: '/#/ontology/zeco', type: 'ontology', hasTable: true, isIndexed: true },
	NCBITaxonTerm: {
		name: 'NCBITaxon',
		link: '/#/ontology/ncbitaxon',
		type: 'ontology',
		hasTable: true,
		isIndexed: true,
	},
	WBLSTerm: { name: 'WBLS', link: '/#/ontology/wbls', type: 'ontology', hasTable: true, isIndexed: true },
	FBDVTerm: { name: 'FBDV', link: '/#/ontology/fbdv', type: 'ontology', hasTable: true, isIndexed: true },
	MMUSDVTerm: { name: 'MMUSDV', link: '/#/ontology/mmusdv', type: 'ontology', hasTable: true, isIndexed: true },
	ZFSTerm: { name: 'ZFS', link: '/#/ontology/zfs', type: 'ontology', hasTable: true, isIndexed: true },
	XPOTerm: { name: 'XPO', link: '/#/ontology/xpo', type: 'ontology', hasTable: true, isIndexed: true },
	ATPTerm: { name: 'ATP', link: '/#/ontology/atp', type: 'ontology', hasTable: true, isIndexed: true },
	VTTerm: { name: 'VT', link: '/#/ontology/vt', type: 'ontology', hasTable: true, isIndexed: true },
	XBEDTerm: { name: 'XBED', link: '/#/ontology/xbed', type: 'ontology', hasTable: true, isIndexed: true },
	OBITerm: { name: 'OBI', link: '/#/ontology/obi', type: 'ontology', hasTable: true, isIndexed: true },
	WBPhenotypeTerm: { name: 'WBPheno', link: '/#/ontology/wbpheno', type: 'ontology', hasTable: true, isIndexed: true },
	PATOTerm: { name: 'PATO', link: '/#/ontology/pato', type: 'ontology', hasTable: true, isIndexed: true },
	HPTerm: { name: 'HP', link: '/#/ontology/hp', type: 'ontology', hasTable: true, isIndexed: true },
	FBCVTerm: { name: 'FBCV', link: '/#/ontology/fbcv', type: 'ontology', hasTable: true, isIndexed: true },
	MMOTerm: { name: 'MMO', link: '/#/ontology/mmo', type: 'ontology', hasTable: true, isIndexed: true },
	APOTerm: { name: 'APO', link: '/#/ontology/apo', type: 'ontology', hasTable: true, isIndexed: true },
	MITerm: { name: 'MI', link: '/#/ontology/mi', type: 'ontology', hasTable: true, isIndexed: true },
	MPATHTerm: { name: 'MPATH', link: '/#/ontology/mpath', type: 'ontology', hasTable: true, isIndexed: true },
	MODTerm: { name: 'MOD', link: '/#/ontology/mod', type: 'ontology', hasTable: true, isIndexed: true },
	UBERONTerm: { name: 'UBERON', link: '/#/ontology/uberon', type: 'ontology', hasTable: true, isIndexed: true },
	RSTerm: { name: 'RS', link: '/#/ontology/rs', type: 'ontology', hasTable: true, isIndexed: true },
	PWTerm: { name: 'PW', link: '/#/ontology/pw', type: 'ontology', hasTable: true, isIndexed: true },
	CLTerm: { name: 'CL', link: '/#/ontology/cl', type: 'ontology', hasTable: true, isIndexed: true },
	CMOTerm: { name: 'CMO', link: '/#/ontology/cmo', type: 'ontology', hasTable: true, isIndexed: true },
	BSPOTerm: { name: 'BSPO', link: '/#/ontology/bspo', type: 'ontology', hasTable: true, isIndexed: true },
	GENOTerm: { name: 'GENO', link: '/#/ontology/geno', type: 'ontology', hasTable: true, isIndexed: true },

	CurationReport: { name: 'Curation Reports', link: '/#/reports', type: 'system', hasTable: true, isIndexed: false },
	BulkLoad: {
		name: 'Bulk Loads / Failed Loads',
		link: '/#/dataloads',
		type: 'system',
		hasTable: true,
		isIndexed: false,
	},

	AlleleGeneAssociation: {
		name: 'Allele Gene Associations',
		type: 'association',
		hasTable: false,
	},
	AlleleVariantAssociation: {
		name: 'Allele Variant Associations',
		type: 'association',
		hasTable: false,
	},
	CodingSequenceGenomicLocationAssociation: {
		name: 'CDS Genomic Locations',
		type: 'association',
		hasTable: false,
	},
	ExonGenomicLocationAssociation: {
		name: 'Exon Genomic Locations',
		type: 'association',
		hasTable: false,
	},
	GeneGenomicLocationAssociation: {
		name: 'Gene Genomic Locations',
		type: 'association',
		hasTable: false,
	},
	TranscriptGenomicLocationAssociation: {
		name: 'Transcript Genomic Locations',
		type: 'association',
		hasTable: false,
	},
	VariantGenomicLocationAssociation: {
		name: 'Variant Genomic Locations',
		type: 'association',
		hasTable: false,
	},
	ConstructGenomicEntityAssociation: {
		name: 'Construct Genomic Entity Associations',
		type: 'association',
		hasTable: false,
	},
	SequenceTargetingReagentGeneAssociation: {
		name: 'SQTR Gene Associations',
		type: 'association',
		hasTable: false,
	},
	TranscriptCodingSequenceAssociation: {
		name: 'Transcript CDS Associations',
		type: 'association',
		hasTable: false,
	},
	TranscriptExonAssociation: {
		name: 'Transcript Exon Associations',
		type: 'association',
		hasTable: false,
	},
	TranscriptGeneAssociation: {
		name: 'Transcript Gene Associations',
		type: 'association',
		hasTable: false,
	},
});
