export const Endpoints = Object.freeze({
	Entity: Object.freeze({
		AGM: 'agm',
		ALLELE: 'allele',
		ALLELE_GENE_ASSOCIATION: 'allelegeneassociation',
		BIOLOGICAL_ENTITY: 'biologicalentity',
		CONSTRUCT: 'construct',
		GENE: 'gene',
		GENOME_ASSEMBLY: 'genomeassembly',
		MOLECULE: 'molecule',
		NOTE: 'note',
		SPECIES: 'species',
		VARIANT: 'variant',
	}),

	Annotation: Object.freeze({
		CONDITION_RELATION: 'condition-relation',
		DISEASE_ANNOTATION: 'disease-annotation',
		EXPERIMENTAL_CONDITION: 'experimental-condition',
		GENE_EXPRESSION_ANNOTATION: 'gene-expression-annotation',
		GENE_GENETIC_INTERACTION: 'gene-genetic-interaction',
		GENE_MOLECULAR_INTERACTION: 'gene-molecular-interaction',
		PHENOTYPE_ANNOTATION: 'phenotype-annotation',
	}),

	SlotAnnotation: Object.freeze({
		ALLELE_DATABASE_STATUS: 'alleledatabasestatusslotannotation',
		ALLELE_FULL_NAME: 'allelefullnameslotannotation',
		ALLELE_FUNCTIONAL_IMPACT: 'allelefunctionalimpactslotannotation',
		ALLELE_GERMLINE_TRANSMISSION_STATUS: 'allelegermlinetransmissionstatusslotannotation',
		ALLELE_INHERITANCE_MODE: 'alleleinheritancemodeslotannotation',
		ALLELE_MUTATION_TYPE: 'allelemutationtypeslotannotation',
		ALLELE_NOMENCLATURE_EVENT: 'allelenomenclatureeventslotannotation',
		ALLELE_SECONDARY_ID: 'allelesecondaryidslotannotation',
		ALLELE_SYMBOL: 'allelesymbolslotannotation',
		ALLELE_SYNONYM: 'allelesynonymslotannotation',
	}),

	Ontology: Object.freeze({
		ANATOMICAL: 'anatomicalterm',
		APO: 'apoterm',
		ATP: 'atpterm',
		BSPO: 'bspoterm',
		BTO: 'btoterm',
		CHEBI: 'chebiterm',
		CHEMICAL: 'chemicalterm',
		CL: 'clterm',
		CMO: 'cmoterm',
		DAO: 'daoterm',
		DO: 'doterm',
		ECO: 'ecoterm',
		EMAPA: 'emapaterm',
		EXPERIMENTAL_CONDITION: 'experimentalconditionontologyterm',
		FBCV: 'fbcvterm',
		FBDV: 'fbdvterm',
		GENO: 'genoterm',
		GO: 'goterm',
		HP: 'hpterm',
		MA: 'materm',
		MI: 'miterm',
		MMUSDV: 'mmusdvterm',
		MMO: 'mmoterm',
		MOD: 'modterm',
		MP: 'mpterm',
		MPATH: 'mpathterm',
		NCBI_TAXON: 'ncbitaxonterm',
		OBI: 'obiterm',
		PATO: 'patoterm',
		PHENOTYPE: 'phenotypeterm',
		PW: 'pwterm',
		RO: 'roterm',
		RS: 'rsterm',
		SO: 'soterm',
		UBERON: 'uberonterm',
		VT: 'vtterm',
		WBBT: 'wbbtterm',
		WBLS: 'wblsterm',
		WB_PHENOTYPE: 'wbphenotypeterm',
		XBA: 'xbaterm',
		XBED: 'xbedterm',
		XBS: 'xbsterm',
		XCO: 'xcoterm',
		XPO: 'xpoterm',
		XSMO: 'xsmoterm',
		ZECO: 'zecoterm',
		ZFA: 'zfaterm',
		ZFS: 'zfsterm',
	}),

	Vocabulary: Object.freeze({
		VOCABULARY: 'vocabulary',
		TERM: 'vocabularyterm',
		TERM_SET: 'vocabularytermset',
	}),

	Document: Object.freeze({
		LITERATURE_REFERENCE: 'literature-reference/document',
	}),

	Resource: Object.freeze({
		DESCRIPTOR: 'resourcedescriptor',
		DESCRIPTOR_PAGE: 'resourcedescriptorpage',
	}),
});
