name: Checkstyle Action
on: pull_request

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle Job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run check style
      uses: dbelyaev/action-checkstyle@master
      with:
        level: 'error'
        fail_on_error: 'true'
        github_token: ${{ secrets.GH_DEVOPS_PAT }}
        reporter: github-pr-review
        checkstyle_config: checkstyle.xml
        checkstyle_version: "10.17.0"
