name: PR validation
on: pull_request
jobs:
  validate-build-api:
    runs-on: ubuntu-20.04
    steps:
      - name: Report workflow details
        run: |
          echo "Repository ${{ github.repository }}."
          echo "Trigger ref ${{ github.ref }}, base-ref ${{ github.base_ref }}, head_ref ${{ github.head_ref }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Report files updated in PR
        run: |
          git fetch origin ${{ github.base_ref }} ${{ github.head_ref }}
          git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Report runtime details
        run: |
          echo "Github runner OS: ${{ runner.os }}"
      - name: Report Maven version
        run: |
          mvn --version
      - name: Run Maven test
        run: |
          mvn --no-transfer-progress test
      - name: Run Maven verify
        run: |
          mvn --batch-mode --update-snapshots verify
