name: PR validation
on: pull_request
jobs:
  validate-build-api:
    runs-on: ubuntu-20.04
    steps:
      - name: Report workflow details
        run: |
          echo "Branch-ref-name ${{ github.ref }}, repository ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Report runtime details
        run: |
          echo "Github runner OS: ${{ runner.os }}, container ${{ job.container }}"
      - name: Report Maven version
        run: |
          mvn --version
      - name: Run Maven test
        run: |
          mvn --no-transfer-progress test
      - name: Run Maven verify
        run: |
          mvn --batch-mode --update-snapshots verify
