name: GitHub Actions PR validation Demo
on: pull_request
jobs:
  validate-build:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Job triggered by a ${{ github.event_name }} event."
      - run: echo "Running on a ${{ runner.os }} Github server."
      - run: echo "Branch-ref-name is ${{ github.ref }}, repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Report Maven version
        run: |
          mvn --version
      - name: Run Maven test
        run: |
          mvn --no-transfer-progress test
      - name: deliberate failure (testing github actions response)
        run: |
          false
      - name: Report ${{ job.status }} status
        run: echo "This job's status is ${{ job.status }}."
